export const mockProfiles = [
  {
    id: "1",
    name: "Riya Sharma",
    age: 24,
    bio: "Looking for someone who's up for good conversations, spontaneous plans and creating amazing memories! ✨",
    jobTitle: "Designer",
    company: "Creatix Studios",
    education: "Symbiosis College, Pune",
    city: "Pune",
    distance: 2.4,
    isVerified: true,
    isOnline: true,
    vibeMatch: 94,
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&h=800&fit=crop",
    photos: [
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&h=800&fit=crop",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&h=800&fit=crop",
    ],
    interests: [
      { name: "Coffee", color: "#8B5E3C", icon: "cafe" },
      { name: "Travel", color: "#3B82F6", icon: "airplane" },
      { name: "Music", color: "#8B5CF6", icon: "musical-notes" },
      { name: "Photography", color: "#10B981", icon: "camera" },
    ],
  },
  {
    id: "2",
    name: "Sneha",
    age: 24,
    bio: "Coffee lover & weekend explorer ☕",
    jobTitle: "Marketing",
    company: "Startup Hub",
    education: "NIT Nagpur",
    city: "Nagpur",
    distance: 2.4,
    isVerified: true,
    isOnline: true,
    vibeMatch: 88,
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&h=800&fit=crop",
    photos: ["https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&h=800&fit=crop"],
    interests: [
      { name: "Coffee", color: "#8B5E3C", icon: "cafe" },
      { name: "Music", color: "#8B5CF6", icon: "musical-notes" },
      { name: "Travel", color: "#3B82F6", icon: "airplane" },
    ],
  },
  {
    id: "3",
    name: "Aman",
    age: 26,
    bio: "Cricket, chai & long drives 🏏",
    jobTitle: "Engineer",
    company: "Tech Corp",
    education: "VIT",
    city: "Nagpur",
    distance: 1.8,
    isVerified: false,
    isOnline: true,
    vibeMatch: 82,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=800&fit=crop",
    photos: ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=800&fit=crop"],
    interests: [
      { name: "Cricket", color: "#22C55E", icon: "baseball" },
      { name: "Coffee", color: "#8B5E3C", icon: "cafe" },
      { name: "Gym", color: "#EF4444", icon: "barbell" },
    ],
  },
  {
    id: "4",
    name: "Karan",
    age: 25,
    bio: "Always down for a movie night 🎬",
    jobTitle: "Developer",
    company: "Freelance",
    education: "Pune University",
    city: "Pune",
    distance: 3.1,
    isVerified: true,
    isOnline: false,
    vibeMatch: 76,
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&h=800&fit=crop",
    photos: ["https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&h=800&fit=crop"],
    interests: [
      { name: "Movie", color: "#6366F1", icon: "film" },
      { name: "Food", color: "#F97316", icon: "pizza" },
    ],
  },
];

export const mockOnlineUsers = [
  { id: "you", name: "You", avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop", isYou: true },
  { id: "2", name: "Aman", avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop", isOnline: true },
  { id: "1", name: "Riya", avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop", isOnline: true },
  { id: "4", name: "Karan", avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop", isOnline: true },
  { id: "3", name: "Sneha", avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&h=200&fit=crop", isOnline: true },
];

export const mockActivities = [
  { id: "1", name: "Coffee", icon: "cafe", color: "#8B5E3C", peopleCount: 12 },
  { id: "2", name: "Food", icon: "pizza", color: "#F97316", peopleCount: 8 },
  { id: "3", name: "Movie", icon: "film", color: "#6366F1", peopleCount: 15 },
  { id: "4", name: "Sports", icon: "tennisball", color: "#22C55E", peopleCount: 6 },
  { id: "5", name: "Bike Ride", icon: "bicycle", color: "#3B82F6", peopleCount: 4 },
];

export const mockHangouts = [
  {
    id: "1",
    title: "Coffee & Chill ☕",
    description: "Let's grab coffee and have good conversations!",
    location: "Cafe Coffee Day, Sitabuldi",
    distance: 3.2,
    scheduledAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    maxParticipants: 8,
    going: 6,
    status: "OPEN",
    badge: "Today",
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=300&fit=crop",
    activity: "Coffee",
    participants: mockOnlineUsers.slice(1, 4),
  },
  {
    id: "2",
    title: "Movie Night 🎬",
    description: "Watching the latest blockbuster together!",
    location: "PVR Cinemas, Nagpur",
    distance: 5.1,
    scheduledAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    maxParticipants: 10,
    going: 4,
    status: "OPEN",
    badge: "Tomorrow",
    imageUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400&h=300&fit=crop",
    activity: "Movie",
    participants: mockOnlineUsers.slice(1, 3),
  },
  {
    id: "3",
    title: "Cricket Match 🏏",
    description: "Friendly cricket match at the ground!",
    location: "VCA Stadium Ground",
    distance: 2.8,
    scheduledAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    maxParticipants: 12,
    going: 8,
    status: "OPEN",
    badge: "This Week",
    imageUrl: "https://images.unsplash.com/photo-1531415075278-85f41f894b20?w=400&h=300&fit=crop",
    activity: "Sports",
    participants: mockOnlineUsers.slice(1, 5),
  },
];

export const mockVibes = [
  { id: "coffee", label: "Coffee", sublabel: "Let's catch up", color: "#F97316", icon: "cafe" },
  { id: "movie", label: "Movie", sublabel: "Watch together", color: "#8B5CF6", icon: "film" },
  { id: "drive", label: "Drive", sublabel: "Long drive?", color: "#3B82F6", icon: "car" },
  { id: "talk", label: "Talk", sublabel: "Deep convo", color: "#EC4899", icon: "chatbubbles" },
  { id: "sports", label: "Sports", sublabel: "Play together", color: "#22C55E", icon: "football" },
];

export const mockQuickActivities = [
  { id: "coffee", name: "Coffee", icon: "cafe", color: "#FEF3C7" },
  { id: "food", name: "Food", icon: "pizza", color: "#FFEDD5" },
  { id: "biryani", name: "Biryani", icon: "restaurant", color: "#FEE2E2" },
  { id: "beer", name: "Beer", icon: "beer", color: "#FEF9C3" },
  { id: "movie", name: "Movie", icon: "film", color: "#E0E7FF" },
  { id: "street", name: "Street", icon: "fast-food", color: "#DCFCE7" },
  { id: "drinks", name: "Drinks", icon: "wine", color: "#FCE7F3" },
  { id: "bike", name: "Bike Ride", icon: "bicycle", color: "#DBEAFE" },
  { id: "sports", name: "Sports", icon: "football", color: "#D1FAE5" },
  { id: "music", name: "Music", icon: "musical-notes", color: "#EDE9FE" },
];
